### ISSUE TITLE
Deterministic $TeamCityBuildNumber when triggering multiple builds

### ISSUE THREAD

**Issue by arisliang** [Inedo/bmx-teamcity#23]
Currently, teamcity build operation will always update $TeamCityBuildNumber. This behavior may not be ideal for concurrent builds scenario.

For example, bm triggers multiple builds concurrently, without the ability to turn off $TeamCityBuildNumber, every build would update this result back to bm when it finishes, and depending on which build finish last, the result of build number would be indeterministic.

**Comment by stevedennis** [comment]
Can you confirm if this was addressed w/ the new style of operations?

**Comment by arisliang** [comment]
How does the new style work now (5.4.2)? I assigned $TeamCityBuildNumber to "Set build number to variable", within the execution itself the build number is set, but I couldn't see it from pipeline progress screen. I recall used to be able to see it from the progress screen, however, tried version 5.2.2, also didn't work.

**Comment by whatatripp** [comment]
This is now a output parameter of the Operation, so this is assigned as a runtime variable. You can use the Set Package Variable  Operation to create a package variable.

**Comment by arisliang** [comment]
Do you have a simple example that demonstrates how to set this?

I tried to set it as release variable and it didn't work. What I did was:
Created a release variable ($BuildNumber, $TeamCityBuildNumber) in the release.
Import TC Artifact operation:
        TeamCity::Import-Artifact
        (
            Credentials: teamcity,
            Project: aaa,
            BuildConfiguration: bbb,
            Artifact: ccc.zip,
            Branch: bm,
            **TeamCityBuildNumber => $TeamCityBuildNumber**
        );

Set-ReleaseVariable BuildNumber
    (
        Value: $TeamCityBuildNumber
    );

With this set, running the package, in the log it says:

TeamCity build number "20" imported.
Setting BuildNumber release variable...
ReleaseNumber: 0.0.10
PackageNumber: 
Variable set.

It seems the release variable has been set, but when from the progress screen, the release variables for both BuildNumber and TeamCityBuildNumber are both empty value.

I tried similar thing with package variable too yesterday, but same result, the variables are left empty as when created, nothing set is passed back to progress screen.

**Comment by whatatripp** [comment]
Thank you for that additional information. There does appear to be a scoping issue, but it only applies to output variables. If you change the Import operation to the following, it should work in the meantime: 

    TeamCity::Import-Artifact
    (
        Credentials: teamcity,
        Project: aaa,
        BuildConfiguration: bbb,
        Artifact: ccc.zip,
        Branch: bm,
        TeamCityBuildNumber => $TempTCBuildNumber
    );

    set $TeamCityBuildNumber = $TempTCBuildNumber;


Can you try that, and let me know if that resolves it?

**Comment by arisliang** [comment]
Tried, but it doesn't solve it.

"set $TeamCityBuildNumber = $TempTCBuildNumber;"
works within the execution plan confirmed by the log. But the $TeamCityBuildNumber outside in the progress screen is still blank.

**Comment by jrasch** [comment]
This should be resolved in BuildMaster v5.6.0 and later.
