### ISSUE TITLE
Fail to import an artifact when the build configuration is in a nested project

### ISSUE THREAD

**Issue by T0T4R4** [Inedo/bmx-teamcity#29]
See pull-request
https://github.com/Inedo/bmx-teamcity/pull/30

**Comment by T0T4R4** [comment]
you would probably want to do something like this instead 

` Index = Array.FindIndex(buildType.ProjectNameParts, p => string.Equals(p, this.ProjectName, StringComparison.OrdinalIgnoreCase))`

**Comment by jrasch** [comment]
Thanks, this is included in the latest release v5.4.4
