### ISSUE TITLE
Unable to provide TeamCity build configuration ID

### ISSUE THREAD

**Issue by protonyx** [Inedo/bmx-teamcity#32]
My desire is to be able to create/trigger releases from our TeamCity builds. Currently, I have a TeamCity build configuration that contains a powershell script that calls into the BuildMaster API to:
- Create a release
- Set release variables (e.g. TeamCity Project Name, Build Configuration Name, Build Number)
- Create a package
- Deploy the package

The BuildMaster plan is based on the TeamCity tutorial in which the first step imports the artifact from a TeamCity build. The issue I am running into, however, is the fact that I must provide the Project Name and Build Configuration name and let the BuildMaster TeamCity plugin do the lookup to resolve the BuildConfigurationId from the TeamCity API. There are TeamCity variables to inject the ID into a build step as a parameter, but no such variable for the Project name and Build configuration name.

I would like to propose adding the Build Configuration ID as one of the available parameters to set in the ImportTeamCityArtifactOperation and removing the Required attributes from Project Name and Build Configuration. I am willing to submit a pull request if needed.

**Comment by jrasch** [comment]
Thanks, this is included in the latest release v5.4.4
