### ISSUE TITLE
ERROR: Could not parse build number

### ISSUE THREAD

**Issue by whatatripp** [Inedo/bmx-teamcity#38]
From @T0T4R4 ..

Please have a look at this log :

Queueing build in TeamCity...
Attempting to resolve build configuration ID from project and name...
Downloading build types...
Build configuration ID resolved to: UConnectNext
Triggering build configuration UConnectNext...
Using branch: release/4.0.4
Build of UConnectNext was triggered successfully.
Waiting for build to complete...
Solutions Team :: Web Apps build #116 successful. TeamCity reports: Success

Import TeamCity $TeamcityArtifactName Artifact of build lastSuccessful on branch $BranchName of project $TeamcityProjectName using configuration "$TeamcityBuildConfigurationName
Importing artifact "UConnect-Next.zip" from TeamCity...
Attempting to resolve build configuration ID from project and name...
Downloading build types...
Build configuration ID resolved to: UConnectNext
Branch name was specified: release/4.0.4
Importing TeamCity artifact "UConnect-Next.zip" from https://teamcityXXXXX/httpAuth/repository/download/UConnectNext/lastSuccessful/UConnect-Next.zip?branch=release%2F4.0.4...
Downloading temp file to "C:\Windows\TEMP\tmp68B0.tmp"...
Importing artifact into BuildMaster...
Removing temp file...
UConnect-Next.zip artifact imported.
Resolving actual build number...
Build number is the predefined constant "lastSuccessful", resolving...
Could not parse actual build number from TeamCity. Exception details: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
— End of stack trace from previous location where exception was thrown —
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Inedo.BuildMasterExtensions.TeamCity.TeamCityArtifactImporter.<GetActualBuildNumber>d__35.MoveNext()
TeamCity build number "" imported.

What could generate this error ?

**Comment by BenLubar** [comment]
Closing as this is probably the same as #40.

@T0T4R4 if I'm mistaken, comment here and I'll re-open it.
