### ISSUE TITLE
Could not parse build number from TeamCity

### ISSUE THREAD

**Issue by Nic0tiN** [Inedo/bmx-teamcity#43]
Hello,

I know this sounds similar to #38 solved by #41 however, my log is slightly different.
Configuration : TeamCity 2017.1.4
BuildMaster: 5.6.11
TeamCity BM Extension: 5.4.6

There are no change scripts to run.
Queueing build in TeamCity...
Attempting to resolve build configuration ID from project and name...
Downloading build types...
Build configuration ID resolved to: Tdb3_Integration
Triggering build configuration Tdb3_Integration...
Build of Tdb3_Integration was triggered successfully.
Waiting for build to complete...
TDB3 build #214 successful. 
TeamCity reports: Tests passed: 54, ignored: 6
Importing artifact "TDB3.zip" from TeamCity...
Importing TeamCity artifact "TDB3.zip" from http://myTCserver/httpAuth/repository/download/Tdb3_Integration/lastSuccessful/TDB3.zip...
Downloading temp file to "C:\Windows\TEMP\tmp4794.tmp"...
Importing artifact into BuildMaster...
Removing temp file...
TDB3.zip artifact imported.
Resolving actual build number...
Build number is the predefined constant "lastSuccessful", resolving...
**Could not parse actual build number from TeamCity. Exception details: System.NullReferenceException: Object reference not set to an instance of an object.**

   at Inedo.BuildMasterExtensions.TeamCity.TeamCityArtifactImporter.<GetActualBuildNumber>d__35.MoveNext()
TeamCity build number "" imported.
Cleaning up...
Cleanup complete.

**Comment by BenLubar** [comment]
@Nic0tiN what does this page look like?

http://myTCserver/httpAuth/app/rest/builds/?locator=buildType:Tdb3_Integration,running:false,status:success,count:1

The BuildMaster extension assumes it will have at least these fields:

```
<builds>
<build number="[some number]"/>
</builds>
```

Does the version generated by your TeamCity look different? (It probably has additional fields, but at least builds->build->number need to be there.)

**Comment by Nic0tiN** [comment]
Hello @BenLubar 
It responds: 
`<builds count="1" href="/app/rest/builds/?locator=buildType:Tdb3_Integration,running:false,status:success,count:1" nextHref="/app/rest/builds/?locator=buildType:Tdb3_Integration,running:false,status:success,count:1,start:1"><build id="254" buildTypeId="Tdb3_Integration" number="218" status="SUCCESS" state="finished" branchName="<default>" defaultBranch="true" href="/app/rest/builds/id:254" webUrl="http://svr-mx-dev01:8084/viewLog.html?buildId=254&buildTypeId=Tdb3_Integration"/></builds>`

**Comment by BenLubar** [comment]
Ah, I see the problem. Fix coming soon.
